<a href="https://colab.research.google.com/github/doannguyenminhtamcuc-ship-it/Data_VN_chapter1/blob/main/Notebook_3_4_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

3.4. Phân tích khoảng cách thu nhập theo giới tính

In [ ]:
import pandas as pd

# Load the Earnings CSV file
earnings_df = pd.read_csv(
    "/content/Earnings OECD INDUSTRY.csv",
    encoding='latin1'
)

# Display first rows
print("Earnings DataFrame head:")
display(earnings_df.head())

Earnings DataFrame head:

,Country,Year,Gender,ACTIVITY,Economic activity,Average monthly earnings $PPP 2021
0,Austria,2024,Total,AUT,Total,6546.981
1,Austria,2024,Total,A,A. Agriculture; forestry and fishing,5176.012
2,Austria,2024,Total,C,C. Manufacturing,7649.804
3,Austria,2024,Total,F,F. Construction,6466.382
4,Austria,2024,Total,G,G. Wholesale and retail trade; repair of motor...,5327.111

3.4.1. Tạo biến khoảng cách thu nhập giữa Nam và Nữ

In [ ]:
print(earnings_df.columns)
earnings_pivoted = earnings_df.pivot_table(index=['Country ', 'Year', 'Economic activity'], columns='Gender', values='Average monthly earnings  $PPP 2021')
earnings_pivoted['Gender Earning Gap'] = earnings_pivoted['Male'] - earnings_pivoted['Female']
earnings_pivoted = earnings_pivoted.fillna(0)
display(earnings_pivoted.head())

Index(['Country ', 'Year', 'Gender', 'ACTIVITY', 'Economic activity',
       'Average monthly earnings  $PPP 2021'],
      dtype='object')

Gender                                                              Female  \
Country  Year Economic activity
Austria  2013 A. Agriculture; forestry and fishing                2470.723
              C. Manufacturing                                    3061.090
              F. Construction                                     3511.694
              G. Wholesale and retail trade; repair of motor ...  2860.581
              H. Transportation and storage                       3450.902

Gender                                                                Male  \
Country  Year Economic activity
Austria  2013 A. Agriculture; forestry and fishing                3362.570
              C. Manufacturing                                    5219.218
              F. Construction                                     4193.623
              G. Wholesale and retail trade; repair of motor ...  4672.344
              H. Transportation and storage                       4711.471

Gender                                                               Total  \
Country  Year Economic activity
Austria  2013 A. Agriculture; forestry and fishing                2996.233
              C. Manufacturing                                    4670.376
              F. Construction                                     4090.182
              G. Wholesale and retail trade; repair of motor ...  3659.367
              H. Transportation and storage                       4479.416

Gender                                                            Gender Earning Gap
Country  Year Economic activity
Austria  2013 A. Agriculture; forestry and fishing                           891.847
              C. Manufacturing                                              2158.128
              F. Construction                                                681.929
              G. Wholesale and retail trade; repair of motor ...            1811.763
              H. Transportation and storage                                 1260.569